/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pv168.agencymanager.swing;

import java.sql.SQLException;
import java.util.Arrays;
import java.util.List;
import java.util.ResourceBundle;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.DataSource;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.TableModel;
import org.apache.commons.dbcp.BasicDataSource;
import pv168.agencymanager.backend.Agent;
import pv168.agencymanager.backend.AgentManagerImpl;
import pv168.agencymanager.backend.Mission;
import pv168.agencymanager.backend.MissionManagerImpl;
import pv168.agencymanager.backend.SpyAgencyManagerImpl;
import pv168.common.DBUtils;
import static pv168.common.DBUtils.date;
import pv168.common.IllegalEntityException;
import pv168.common.ServiceFailureException;

/**
 *
 * @author vlado
 */
public class Main extends javax.swing.JFrame {

    private ResourceBundle strings = ResourceBundle.getBundle("pv168.agencymanager.swing.Strings", getLocale());
    private DataSource ds;
    private SpyAgencyManagerImpl spyAgencyManager = new SpyAgencyManagerImpl();
    private AgentManagerImpl agentManager = new AgentManagerImpl();
    private MissionManagerImpl missionManager = new MissionManagerImpl();
    public static final Logger logger = Logger.getLogger(Main.class.getName());

    private enum ComboBoxEnum {

        ALL_AGENTS, ALL_MISSIONS, UNASSIGNED_AGENTS, FREE_MISSIONS;
    }

    private enum TableModelsEnum {

        AGENTS_TABLE_MODEL, MISSIONS_TABLE_MODEL;
    }

    /**
     * Creates new form Main
     */
    public Main() {
        //initialize components and data sources
        initComponents();
        jScrollPaneResultTable.setVisible(false);
        ds = prepareDataSource();
        spyAgencyManager.setDataSource(ds);
        agentManager.setDataSource(ds);
        missionManager.setDataSource(ds);

        refreshJComboBoxes();
        refreshTable(TableModelsEnum.AGENTS_TABLE_MODEL);
        refreshTable(TableModelsEnum.MISSIONS_TABLE_MODEL);

        // Localization of GUI elements
        jTabbedPane.setTitleAt(0, strings.getString("agents"));
        jTabbedPane.setTitleAt(1, strings.getString("missions"));

        jTabbedPaneOperations.setTitleAt(0, strings.getString("agents"));
        jTabbedPaneOperations.setTitleAt(1, strings.getString("missions"));
        jTabbedPaneOperations.setTitleAt(2, strings.getString("searchAssignments"));
        jTabbedPaneOperations.setTitleAt(3, strings.getString("manageAssignments"));

        jButtonNewAgent.setText(strings.getString("newAgent"));
        jButtonNewMission.setText(strings.getString("newMission"));
        jButtonDeleteAgent.setText(strings.getString("deleteAgent"));
        jButtonDeleteMission.setText(strings.getString("deleteMission"));
        jButtonFindAssignedAgents.setText(strings.getString("findAssignedAgents"));
        jButtonFindAssignedMission.setText(strings.getString("findAssignedMissions"));
        jButtonFindUnassignedAgents.setText(strings.getString("findUnassignedAgents"));
        jButtonFindMissionsWithFreeSpace.setText(strings.getString("findMissionsWithFreeSpace"));
        jButtonRemoveAgentFromMission.setText(strings.getString("removeAgentFromMission"));
        jButtonAssignAgentOnMission.setText(strings.getString("assignAgentOnMission"));

        jComboBoxAssignAgent.setToolTipText(strings.getString("selectAgent"));
        jComboBoxDeleteAgent.setToolTipText(strings.getString("selectAgent"));
        jComboBoxSearchAgent.setToolTipText(strings.getString("selectAgent"));
        jComboBoxAssignMission.setToolTipText(strings.getString("selectMission"));
        jComboBoxDeleteMission.setToolTipText(strings.getString("selectMission"));
        jComboBoxSearchMission.setToolTipText(strings.getString("selectMission"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        jTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAgents = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMissions = new javax.swing.JTable();
        jTabbedPaneOperations = new javax.swing.JTabbedPane();
        jPanelAgents = new javax.swing.JPanel();
        jButtonNewAgent = new javax.swing.JButton();
        jComboBoxDeleteAgent = new javax.swing.JComboBox();
        jButtonDeleteAgent = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelMissions = new javax.swing.JPanel();
        jButtonNewMission = new javax.swing.JButton();
        jComboBoxDeleteMission = new javax.swing.JComboBox();
        jButtonDeleteMission = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelSearchAssignments = new javax.swing.JPanel();
        jButtonFindUnassignedAgents = new javax.swing.JButton();
        jButtonFindMissionsWithFreeSpace = new javax.swing.JButton();
        jLabelSearchAgent = new javax.swing.JLabel();
        jLabelSearchMission = new javax.swing.JLabel();
        jComboBoxSearchAgent = new javax.swing.JComboBox();
        jComboBoxSearchMission = new javax.swing.JComboBox();
        jButtonFindAssignedMission = new javax.swing.JButton();
        jButtonFindAssignedAgents = new javax.swing.JButton();
        jPanelManageAssignments = new javax.swing.JPanel();
        jComboBoxAssignAgent = new javax.swing.JComboBox();
        jComboBoxAssignMission = new javax.swing.JComboBox();
        jLabelSelectAgent = new javax.swing.JLabel();
        jLabelSelectMission = new javax.swing.JLabel();
        jButtonAssignAgentOnMission = new javax.swing.JButton();
        jButtonRemoveAgentFromMission = new javax.swing.JButton();
        jScrollPaneResultTable = new javax.swing.JScrollPane();
        jTableQueryResult = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.setMinimumSize(new java.awt.Dimension(470, 108));

        jTableAgents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Long(1), "James Bond",  new Integer(7), "1980-01-01", null},
                { new Long(2), "Janko Hrasko",  new Integer(100), "2000-02-02",  new Boolean(true)},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Agent Number", "Date of Enrollment", "Is Dead"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAgents);

        jTabbedPane.addTab("Agents", jScrollPane1);

        jTableMissions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Long(100), "Stary Otec", "2014-01-01",  new Integer(3),  new Boolean(true), "Get rid of that famous person"},
                { new Long(200), "Jastrab", "2014-03-20",  new Integer(1),  new Boolean(true), "Regulerna sledovacka"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "CodeName", "Date Created", "Max num Agents", "In Progress", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableMissions);

        jTabbedPane.addTab("Missions", jScrollPane2);

        jButtonNewAgent.setText("New Agent");
        jButtonNewAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewAgentActionPerformed(evt);
            }
        });

        jComboBoxDeleteAgent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "James Bond", "Janko Hrasko" }));

        jButtonDeleteAgent.setText("Delete selected Agent");
        jButtonDeleteAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAgentActionPerformed(evt);
            }
        });

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgentsLayout = new javax.swing.GroupLayout(jPanelAgents);
        jPanelAgents.setLayout(jPanelAgentsLayout);
        jPanelAgentsLayout.setHorizontalGroup(
            jPanelAgentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAgentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNewAgent)
                    .addGroup(jPanelAgentsLayout.createSequentialGroup()
                        .addComponent(jComboBoxDeleteAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeleteAgent))
                    .addComponent(jButton1))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanelAgentsLayout.setVerticalGroup(
            jPanelAgentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNewAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAgentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDeleteAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPaneOperations.addTab("Agents", jPanelAgents);

        jButtonNewMission.setText("New Mission");
        jButtonNewMission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewMissionActionPerformed(evt);
            }
        });

        jComboBoxDeleteMission.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stary Otec", "Jastrab" }));

        jButtonDeleteMission.setText("Delete Selected Mission");
        jButtonDeleteMission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteMissionActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMissionsLayout = new javax.swing.GroupLayout(jPanelMissions);
        jPanelMissions.setLayout(jPanelMissionsLayout);
        jPanelMissionsLayout.setHorizontalGroup(
            jPanelMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMissionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNewMission)
                    .addGroup(jPanelMissionsLayout.createSequentialGroup()
                        .addComponent(jComboBoxDeleteMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteMission))
                    .addComponent(jButton2))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanelMissionsLayout.setVerticalGroup(
            jPanelMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMissionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNewMission)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDeleteMission)
                    .addComponent(jComboBoxDeleteMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPaneOperations.addTab("Missions", jPanelMissions);

        jButtonFindUnassignedAgents.setText("Find Unassigned Agents");
        jButtonFindUnassignedAgents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindUnassignedAgentsActionPerformed(evt);
            }
        });

        jButtonFindMissionsWithFreeSpace.setText("Find Missions with free space");
        jButtonFindMissionsWithFreeSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindMissionsWithFreeSpaceActionPerformed(evt);
            }
        });

        jLabelSearchAgent.setText("Select Agent:");

        jLabelSearchMission.setText("Select Mission:");

        jComboBoxSearchAgent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "James Bond", "Janko Hrasko" }));

        jComboBoxSearchMission.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stary Otec", "Jastrab" }));

        jButtonFindAssignedMission.setText("Find Mission assigned to Agent");
        jButtonFindAssignedMission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindAssignedMissionActionPerformed(evt);
            }
        });

        jButtonFindAssignedAgents.setText("Find Agents assigned to Mission");
        jButtonFindAssignedAgents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindAssignedAgentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchAssignmentsLayout = new javax.swing.GroupLayout(jPanelSearchAssignments);
        jPanelSearchAssignments.setLayout(jPanelSearchAssignmentsLayout);
        jPanelSearchAssignmentsLayout.setHorizontalGroup(
            jPanelSearchAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchAssignmentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSearchAssignmentsLayout.createSequentialGroup()
                        .addComponent(jButtonFindUnassignedAgents)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFindMissionsWithFreeSpace))
                    .addGroup(jPanelSearchAssignmentsLayout.createSequentialGroup()
                        .addGroup(jPanelSearchAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSearchMission)
                            .addComponent(jLabelSearchAgent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSearchAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSearchAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSearchMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelSearchAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFindAssignedAgents)
                            .addComponent(jButtonFindAssignedMission))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSearchAssignmentsLayout.setVerticalGroup(
            jPanelSearchAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchAssignmentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFindUnassignedAgents)
                    .addComponent(jButtonFindMissionsWithFreeSpace))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSearchAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearchAgent)
                    .addComponent(jComboBoxSearchAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFindAssignedMission))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSearchAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearchMission)
                    .addComponent(jComboBoxSearchMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFindAssignedAgents))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPaneOperations.addTab("Search Assignments", jPanelSearchAssignments);

        jComboBoxAssignAgent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "James Bond", "Janko Hrasko" }));

        jComboBoxAssignMission.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stary Otec", "Jastrab" }));

        jLabelSelectAgent.setText("Select Agent:");

        jLabelSelectMission.setText("Select Mission:");

        jButtonAssignAgentOnMission.setText("Assign Agent on a Mission");
        jButtonAssignAgentOnMission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAssignAgentOnMissionActionPerformed(evt);
            }
        });

        jButtonRemoveAgentFromMission.setText("Remove Agent from Mission");
        jButtonRemoveAgentFromMission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveAgentFromMissionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelManageAssignmentsLayout = new javax.swing.GroupLayout(jPanelManageAssignments);
        jPanelManageAssignments.setLayout(jPanelManageAssignmentsLayout);
        jPanelManageAssignmentsLayout.setHorizontalGroup(
            jPanelManageAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageAssignmentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelManageAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSelectAgent)
                    .addComponent(jLabelSelectMission))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelManageAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxAssignAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAssignMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelManageAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRemoveAgentFromMission)
                    .addComponent(jButtonAssignAgentOnMission))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelManageAssignmentsLayout.setVerticalGroup(
            jPanelManageAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageAssignmentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelManageAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAssignAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSelectAgent)
                    .addComponent(jButtonAssignAgentOnMission))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelManageAssignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAssignMission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSelectMission)
                    .addComponent(jButtonRemoveAgentFromMission))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPaneOperations.addTab("Manage Assignments", jPanelManageAssignments);

        jTableQueryResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Query Result Table"}
            },
            new String [] {
                "null"
            }
        ));
        jScrollPaneResultTable.setViewportView(jTableQueryResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPaneOperations)
                    .addComponent(jScrollPaneResultTable)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneOperations, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneResultTable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewAgentActionPerformed
        NewAgentDialog dialog = new NewAgentDialog(null, true, strings, agentManager);
        dialog.setVisible(true);
        refreshTable(TableModelsEnum.AGENTS_TABLE_MODEL);
        refreshJComboBoxes();
    }//GEN-LAST:event_jButtonNewAgentActionPerformed

    private void jButtonNewMissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewMissionActionPerformed
        NewMissionDialog dialog = new NewMissionDialog(null, true, strings, missionManager);
        dialog.setVisible(true);
        refreshTable(TableModelsEnum.MISSIONS_TABLE_MODEL);
        refreshJComboBoxes();
    }//GEN-LAST:event_jButtonNewMissionActionPerformed

    private void jButtonDeleteAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAgentActionPerformed
        AgentSwingWorker worker = new AgentSwingWorker(AgentActionsEnum.REMOVE_AGENT);
        worker.execute();
    }//GEN-LAST:event_jButtonDeleteAgentActionPerformed

    private void jButtonFindUnassignedAgentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindUnassignedAgentsActionPerformed
        AgentSwingWorker worker = new AgentSwingWorker(AgentActionsEnum.FIND_UNASSIGNED_AGENTS);
        worker.execute();
    }//GEN-LAST:event_jButtonFindUnassignedAgentsActionPerformed

    private void jButtonFindMissionsWithFreeSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindMissionsWithFreeSpaceActionPerformed
        MissionSwingWorker worker = new MissionSwingWorker(MissionActionsEnum.FIND_FREE_MISSIONS);
        worker.execute();
    }//GEN-LAST:event_jButtonFindMissionsWithFreeSpaceActionPerformed

    private void jButtonFindAssignedMissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindAssignedMissionActionPerformed
        MissionSwingWorker worker = new MissionSwingWorker(MissionActionsEnum.FIND_ASSIGNED_MISSION);
        worker.execute();
    }//GEN-LAST:event_jButtonFindAssignedMissionActionPerformed

    private void jButtonFindAssignedAgentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindAssignedAgentsActionPerformed
        AgentSwingWorker worker = new AgentSwingWorker(AgentActionsEnum.FIND_ASSIGNED_AGENTS);
        worker.execute();
    }//GEN-LAST:event_jButtonFindAssignedAgentsActionPerformed

    private void jButtonDeleteMissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteMissionActionPerformed
        MissionSwingWorker worker = new MissionSwingWorker(MissionActionsEnum.REMOVE_MISSION);
        worker.execute();
    }//GEN-LAST:event_jButtonDeleteMissionActionPerformed

    private void jButtonAssignAgentOnMissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAssignAgentOnMissionActionPerformed
        AssignmentSwingWorker worker = new AssignmentSwingWorker(AssignmentsActionsEnum.ASSIGN_AGENT_ON_MISSION);
        worker.execute();
    }//GEN-LAST:event_jButtonAssignAgentOnMissionActionPerformed

    private void jButtonRemoveAgentFromMissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveAgentFromMissionActionPerformed
        AssignmentSwingWorker worker = new AssignmentSwingWorker(AssignmentsActionsEnum.REMOVE_AGENT_FROM_MISSION);
        worker.execute();
    }//GEN-LAST:event_jButtonRemoveAgentFromMissionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AgentSwingWorker worker = new AgentSwingWorker(AgentActionsEnum.UPDATE_AGENT);
        worker.execute();  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MissionSwingWorker worker = new MissionSwingWorker(MissionActionsEnum.UPDATE_MISSION);
        worker.execute();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAssignAgentOnMission;
    private javax.swing.JButton jButtonDeleteAgent;
    private javax.swing.JButton jButtonDeleteMission;
    private javax.swing.JButton jButtonFindAssignedAgents;
    private javax.swing.JButton jButtonFindAssignedMission;
    private javax.swing.JButton jButtonFindMissionsWithFreeSpace;
    private javax.swing.JButton jButtonFindUnassignedAgents;
    private javax.swing.JButton jButtonNewAgent;
    private javax.swing.JButton jButtonNewMission;
    private javax.swing.JButton jButtonRemoveAgentFromMission;
    private javax.swing.JComboBox jComboBoxAssignAgent;
    private javax.swing.JComboBox jComboBoxAssignMission;
    private javax.swing.JComboBox jComboBoxDeleteAgent;
    private javax.swing.JComboBox jComboBoxDeleteMission;
    private javax.swing.JComboBox jComboBoxSearchAgent;
    private javax.swing.JComboBox jComboBoxSearchMission;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabelSearchAgent;
    private javax.swing.JLabel jLabelSearchMission;
    private javax.swing.JLabel jLabelSelectAgent;
    private javax.swing.JLabel jLabelSelectMission;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanelAgents;
    private javax.swing.JPanel jPanelManageAssignments;
    private javax.swing.JPanel jPanelMissions;
    private javax.swing.JPanel jPanelSearchAssignments;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneResultTable;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTabbedPane jTabbedPaneOperations;
    private javax.swing.JTable jTableAgents;
    private javax.swing.JTable jTableMissions;
    private javax.swing.JTable jTableQueryResult;
    // End of variables declaration//GEN-END:variables

    private DataSource prepareDataSource() {
        ResourceBundle dsBundle = ResourceBundle.getBundle("pv168.agencymanager.swing.Database");
        String url = dsBundle.getString("jdbc.url");
        String username = dsBundle.getString("jdbc.username");
        String password = dsBundle.getString("jdbc.password");

        BasicDataSource newDs = new BasicDataSource();
        newDs.setUrl(url);
        newDs.setUsername(username);
        newDs.setPassword(password);

//        try {
            //DBUtils.tryCreateTables(newDs, new URL("pv168.agencymanager.backend.createTables.sql"));
           // DBUtils.tryCreateTables(newDs, Main.class.getResource("/pv168/agencymanager/backend/createTables.sql"));
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(rootPane, "Error creating tables.", "Error", JOptionPane.ERROR_MESSAGE);
//            logger.log(Level.SEVERE, "Error creating tables");
//            System.exit(1);
//        }

        return newDs;
    }

    private String[] getJComboBoxValues(ComboBoxEnum mode) throws ServiceFailureException {
        int i = 0;
        String[] resultArray = null;

        switch (mode) {
            case ALL_AGENTS:
                resultArray = new String[agentManager.getAllAgents().size()];
                for (Agent agent : agentManager.getAllAgents()) {
                    resultArray[i] = agent.getName() + " (" + agent.getAgentNumber() + ")";
                    i++;
                }
                break;
            case ALL_MISSIONS:
                resultArray = new String[missionManager.getAllMissions().size()];
                for (Mission mission : missionManager.getAllMissions()) {
                    resultArray[i] = mission.getCodeName();
                    i++;
                }
                break;
            case UNASSIGNED_AGENTS:
                resultArray = new String[spyAgencyManager.findUnassignedAgents().size()];
                for (Agent agent : spyAgencyManager.findUnassignedAgents()) {
                    resultArray[i] = agent.getName() + " (" + agent.getAgentNumber() + ")";
                    i++;
                }
                break;
            case FREE_MISSIONS:
                resultArray = new String[spyAgencyManager.findMissionsWithSomeFreeSpace().size()];
                for (Mission mission : spyAgencyManager.findMissionsWithSomeFreeSpace()) {
                    resultArray[i] = mission.getCodeName();
                    i++;
                }
                break;
        }

        return (resultArray == null ? new String[0] : resultArray);
    }

    private void refreshJComboBoxes() {
        try {
            jComboBoxDeleteAgent.setModel(new DefaultComboBoxModel(getJComboBoxValues(ComboBoxEnum.ALL_AGENTS)));
            if (jComboBoxDeleteAgent.getSelectedItem() == null) {
                jButtonDeleteAgent.setEnabled(false);
            } else {
                jButtonDeleteAgent.setEnabled(true);
            }
            jComboBoxDeleteMission.setModel(new DefaultComboBoxModel(getJComboBoxValues(ComboBoxEnum.ALL_MISSIONS)));
            if (jComboBoxDeleteMission.getSelectedItem() == null) {
                jButtonDeleteMission.setEnabled(false);
            } else {
                jButtonDeleteMission.setEnabled(true);
            }
            jComboBoxAssignAgent.setModel(new DefaultComboBoxModel(getJComboBoxValues(ComboBoxEnum.ALL_AGENTS)));
            if (jComboBoxAssignAgent.getSelectedItem() == null || jComboBoxAssignMission.getSelectedItem() == null) {
                jButtonAssignAgentOnMission.setEnabled(false);
                jButtonRemoveAgentFromMission.setEnabled(false);
            } else {
                jButtonAssignAgentOnMission.setEnabled(true);
                jButtonRemoveAgentFromMission.setEnabled(true);
            }
            jComboBoxAssignMission.setModel(new DefaultComboBoxModel(getJComboBoxValues(ComboBoxEnum.ALL_MISSIONS)));
            if (jComboBoxAssignMission.getSelectedItem() == null || jComboBoxAssignAgent.getSelectedItem() == null) {
                jButtonAssignAgentOnMission.setEnabled(false);
                jButtonRemoveAgentFromMission.setEnabled(false);
            } else {
                jButtonAssignAgentOnMission.setEnabled(true);
                jButtonRemoveAgentFromMission.setEnabled(true);
            }
            jComboBoxSearchAgent.setModel(new DefaultComboBoxModel(getJComboBoxValues(ComboBoxEnum.ALL_AGENTS)));
            if (jComboBoxSearchAgent.getSelectedItem() == null || jComboBoxSearchMission.getSelectedItem() == null) {
                jButtonFindAssignedMission.setEnabled(false);
            } else {
                jButtonFindAssignedMission.setEnabled(true);
            }
            jComboBoxSearchMission.setModel(new DefaultComboBoxModel(getJComboBoxValues(ComboBoxEnum.ALL_MISSIONS)));
            if (jComboBoxSearchMission.getSelectedItem() == null || jComboBoxSearchAgent.getSelectedItem() == null) {
                jButtonFindAssignedAgents.setEnabled(false);
            } else {
                jButtonFindAssignedAgents.setEnabled(true);
            }
        } catch (ServiceFailureException ex) {
            logger.log(Level.SEVERE, "Exception while refreshing combo boxes.", ex);
        }
    }

    private void refreshTable(TableModelsEnum model) {
        switch (model) {
            case AGENTS_TABLE_MODEL:
                try {
                    //AgentsTableModel tm = (AgentsTableModel) model;
                    AgentsTableModel tm = new AgentsTableModel(strings);
                    tm.addAll(agentManager.getAllAgents());
                    jTableAgents.setModel(tm);
                    break;
                } catch (ServiceFailureException ex) {
                    logger.log(Level.SEVERE, "Exception while refreshing Agents table.", ex);
                }
            case MISSIONS_TABLE_MODEL:
                try {
                    //MissionsTableModel tm = (MissionsTableModel) model;
                    MissionsTableModel tm = new MissionsTableModel(strings);
                    tm.addAll(missionManager.getAllMissions());
                    jTableMissions.setModel(tm);
                    break;
                } catch (ServiceFailureException ex) {
                    logger.log(Level.SEVERE, "Exception while refreshing Missions table.", ex);
                }
        }
    }

    private Integer getAgentNumberFromComboBoxValue(String selectedValue) {
        String[] parts = selectedValue.split("\\(|\\)");
        return Integer.parseInt(parts[parts.length - 1]);
    }

    private void showQuerryTable(TableModel model) {
        jTableQueryResult.setModel(model);
        jScrollPaneResultTable.setVisible(true);
        revalidate();
        repaint();
    }

    private boolean checkAssignment(Agent agent, Mission mission) {
        try {
            List<Agent> assignedAgents = spyAgencyManager.getAgentsOnMission(mission);
            return assignedAgents.contains(agent);
        } catch (ServiceFailureException | IllegalEntityException ex) {
            logger.log(Level.SEVERE, "Exception while getting list of assigned Agents", ex);
        }
        return false;
    }

    private boolean checkIfUnassigned(Agent agent) {
        try {
            List<Agent> agents = spyAgencyManager.findUnassignedAgents();
            return agents.contains(agent);
        } catch (ServiceFailureException ex) {
            logger.log(Level.SEVERE, "Exception while checking availability of agent.", ex);
        }
        return false;
    }

    private boolean checkIfHasSpace(Mission mission) {
        try {
            List<Mission> missions = spyAgencyManager.findMissionsWithSomeFreeSpace();
            return missions.contains(mission);
        } catch (ServiceFailureException ex) {
            logger.log(Level.SEVERE, "Exception while checking free space of mission.", ex);
        }
        return false;
    }

    private boolean checkSafeToRemoveMission(Mission mission) {
        try {
            List<Agent> agentsOnMission = spyAgencyManager.getAgentsOnMission(mission);
            return agentsOnMission.isEmpty();
        } catch (ServiceFailureException | IllegalEntityException ex) {
            logger.log(Level.SEVERE, "Exception while checking safety of mission removal.", ex);
        }
        return false;
    }

    private enum AgentActionsEnum {

        REMOVE_AGENT, FIND_UNASSIGNED_AGENTS, FIND_ASSIGNED_AGENTS, UPDATE_AGENT;
    }

    private enum MissionActionsEnum {

        REMOVE_MISSION, FIND_FREE_MISSIONS, FIND_ASSIGNED_MISSION, UPDATE_MISSION;
    }

    private enum AssignmentsActionsEnum {

        ASSIGN_AGENT_ON_MISSION, REMOVE_AGENT_FROM_MISSION;
    }

    private class AgentSwingWorker extends SwingWorker<AgentsTableModel, Void> {

        AgentActionsEnum actions;

        public AgentSwingWorker(AgentActionsEnum actions) {
            this.actions = actions;
        }

        @Override
        protected AgentsTableModel doInBackground() throws Exception {
            switch (actions) {
                case UPDATE_AGENT:
                    try{
                        Integer number = getAgentNumberFromComboBoxValue((String) jComboBoxDeleteAgent.getSelectedItem());
                        Agent updateAgent = agentManager.findAgentByAgentNumber(number);
                        updateAgent.setName(JOptionPane.showInputDialog("Enter new name."));
                        //updateAgent.setAgentNumber(JOptionPane.showInputDialog("Enter new number."));
                        agentManager.updateAgent(updateAgent);
                        break;                    
                    } catch (ServiceFailureException ex){
                        logger.log(Level.SEVERE, "Exception while updating agent.", ex);
                    }
                case REMOVE_AGENT:
                    try {
                        Integer number = getAgentNumberFromComboBoxValue((String) jComboBoxDeleteAgent.getSelectedItem());
                        Agent deleteAgent = agentManager.findAgentByAgentNumber(number);
                        agentManager.dismissAgent(deleteAgent);
                        break;
                    } catch (ServiceFailureException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                case FIND_UNASSIGNED_AGENTS:
                    try {
                        AgentsTableModel tm = new AgentsTableModel(strings);
                        tm.addAll(spyAgencyManager.findUnassignedAgents());
                        return tm;
                    } catch (ServiceFailureException ex) {
                        logger.log(Level.SEVERE, "Exception while getting unassigned agents from database.", ex);
                    }
                case FIND_ASSIGNED_AGENTS:
                    try {
                        AgentsTableModel tm = new AgentsTableModel(strings);
                        tm.addAll(spyAgencyManager.getAgentsOnMission(missionManager
                                .findMissionByCodeName((String) jComboBoxSearchMission.getSelectedItem())));
                        return tm;
                    } catch (ServiceFailureException ex) {
                        logger.log(Level.SEVERE, "Exception while getting agents assigned to mission from database.", ex);
                    }
                    break;
            }

            return null;
        }

        @Override
        protected void done() {
            switch (actions) {
                case UPDATE_AGENT:
                    refreshTable(TableModelsEnum.AGENTS_TABLE_MODEL);
                    refreshJComboBoxes();
                    break;
                case REMOVE_AGENT:
                    refreshTable(TableModelsEnum.AGENTS_TABLE_MODEL);
                    refreshJComboBoxes();
                    break;
                case FIND_UNASSIGNED_AGENTS:
                    try {
                        showQuerryTable(get());
                    } catch (InterruptedException | ExecutionException ex) {
                        logger.log(Level.SEVERE, "Exception while getting table model in get() method.", ex);
                    }
                    break;
                case FIND_ASSIGNED_AGENTS:
                    try {
                        showQuerryTable(get());
                    } catch (InterruptedException | ExecutionException ex) {
                        logger.log(Level.SEVERE, "Exception while getting table model in done() method.", ex);
                    }
                    break;
            }
        }

    }

    private class MissionSwingWorker extends SwingWorker<MissionsTableModel, Void> {

        MissionActionsEnum actions;

        public MissionSwingWorker(MissionActionsEnum actions) {
            this.actions = actions;
        }

        @Override
        protected MissionsTableModel doInBackground() throws Exception {
            switch (actions) {
                    case UPDATE_MISSION:
                    try{
                        Mission updateMission = missionManager.findMissionByCodeName((String) jComboBoxDeleteMission.getSelectedItem());
                        updateMission.setCodeName(JOptionPane.showInputDialog("Enter new name."));
                        //updateAgent.setAgentNumber(JOptionPane.showInputDialog("Enter new number."));
                        missionManager.updateMission(updateMission);
                        break;                    
                    } catch (ServiceFailureException ex){
                        logger.log(Level.SEVERE, "Exception while updating mission.", ex);
                    }
                case REMOVE_MISSION:
                    try {
                        Mission deleteMission = missionManager.findMissionByCodeName((String) jComboBoxDeleteMission.getSelectedItem());
                        if (checkSafeToRemoveMission(deleteMission)) {
                            missionManager.removeMission(deleteMission);
                            return new MissionsTableModel(strings);
                        } else {
                            return null;
                        }
                    } catch (ServiceFailureException ex) {
                        logger.log(Level.SEVERE, "Exception while deleting mission from database", ex);
                    }
                    break;
                case FIND_FREE_MISSIONS:
                    try {
                        MissionsTableModel tm = new MissionsTableModel(strings);
                        tm.addAll(spyAgencyManager.findMissionsWithSomeFreeSpace());
                        return tm;
                    } catch (ServiceFailureException ex) {
                        logger.log(Level.SEVERE, "Exception while getting missions with free space from database.", ex);
                    }
                    break;
                case FIND_ASSIGNED_MISSION:
                    try {
                        MissionsTableModel tm = new MissionsTableModel(strings);
                        Mission mission = spyAgencyManager.findMissionWithAgent(agentManager
                                .findAgentByAgentNumber(getAgentNumberFromComboBoxValue(
                                                (String) jComboBoxSearchAgent.getSelectedItem())));
//                        tm.add(spyAgencyManager.findMissionWithAgent(agentManager
//                                .findAgentByAgentNumber(getAgentNumberFromComboBoxValue(
//                                                (String) jComboBoxSearchAgent.getSelectedItem()))));
                        if (mission != null) {
                            tm.add(mission);
                            return tm;
                        } else {
                            return null;
                        }
                    } catch (ServiceFailureException ex) {
                        logger.log(Level.SEVERE, "Exception while getting assigned mission to agent from database.", ex);
                    }
                    break;
            }

            return null;
        }

        @Override
        protected void done() {
            switch (actions) {
                case UPDATE_MISSION:
                    refreshTable(TableModelsEnum.MISSIONS_TABLE_MODEL);
                    refreshJComboBoxes();
                    break;
                case REMOVE_MISSION:
                    try {
                        if (get() != null) {
                            refreshTable(TableModelsEnum.MISSIONS_TABLE_MODEL);
                            refreshJComboBoxes();
                        } else {
                            JOptionPane.showMessageDialog(null, "Selected mission has assigned agents!", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (InterruptedException | ExecutionException ex) {
                        logger.log(Level.SEVERE, "Exception while getting table model in done() method.", ex);
                    }
                    break;
                case FIND_FREE_MISSIONS:
                    try {
                        showQuerryTable(get());
                    } catch (InterruptedException | ExecutionException ex) {
                        logger.log(Level.SEVERE, "Exception while getting table model in get() method.", ex);
                    }
                    break;
                case FIND_ASSIGNED_MISSION:
                    try {
                        if (get() != null) {
                            showQuerryTable(get());
                        } else {
                            JOptionPane.showMessageDialog(null, "Selected Agent is not assigned on any mission.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (InterruptedException | ExecutionException ex) {
                        logger.log(Level.SEVERE, "Exception while getting table model in done() method.", ex);
                    }
                    break;
            }
        }
    }

    private class AssignmentSwingWorker extends SwingWorker<Boolean, Void> {

        AssignmentsActionsEnum actions;

        public AssignmentSwingWorker(AssignmentsActionsEnum actions) {
            this.actions = actions;
        }

        @Override
        protected Boolean doInBackground() throws Exception {
            switch (actions) {
                case ASSIGN_AGENT_ON_MISSION:
                    try {
                        Agent agent = agentManager.findAgentByAgentNumber(
                                getAgentNumberFromComboBoxValue((String) jComboBoxAssignAgent.getSelectedItem()));
                        Mission mission = missionManager.findMissionByCodeName((String) jComboBoxAssignMission.getSelectedItem());
                        if (checkIfUnassigned(agent) && checkIfHasSpace(mission)) {
                            spyAgencyManager.assignAgentOnMission(agent, mission);
                            return true;
                        } else {
                            return false;
                        }
                    } catch (ServiceFailureException ex) {
                        logger.log(Level.SEVERE, "Exception while assigning agent on a mission", ex);
                    }
                    break;
                case REMOVE_AGENT_FROM_MISSION:
                    try {
                        Agent agent = agentManager.findAgentByAgentNumber(
                                getAgentNumberFromComboBoxValue((String) jComboBoxAssignAgent.getSelectedItem()));
                        Mission mission = missionManager.findMissionByCodeName((String) jComboBoxAssignMission.getSelectedItem());
                        if (checkAssignment(agent, mission)) {
                            spyAgencyManager.removeAgentFromMission(agent, mission);
                            return true;
                        } else {
                            return false;
                        }
                    } catch (ServiceFailureException ex) {
                        logger.log(Level.SEVERE, "Exception while removing agent from a mission", ex);
                    }
                    break;
            }
            return false;
        }

        @Override
        protected void done() {
            switch (actions) {
                case ASSIGN_AGENT_ON_MISSION:
                    try {
                        if (get()) {
                            JOptionPane.showMessageDialog(null, "Agent successfuly assigned on a Mission.");
                        } else {
                            JOptionPane.showMessageDialog(null, "Selected agent is already assigned and/or selected mission is full!", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (InterruptedException | ExecutionException ex) {
                        logger.log(Level.SEVERE, "Exception while getting boolean in done() method.", ex);
                    }
                    break;
                case REMOVE_AGENT_FROM_MISSION:
                    try {
                        if (get()) {
                            JOptionPane.showMessageDialog(null, "Agent successfuly removed from Mission.");
                        } else {
                            JOptionPane.showMessageDialog(null, "Selected agent is not assigned on selected Mission!", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (InterruptedException | ExecutionException ex) {
                        logger.log(Level.SEVERE, "Exception while getting boolean in done() method.s", ex);
                    }
                    break;
            }
        }

    }
}
