/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pv168.agencymanager.swing;

import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import pv168.agencymanager.backend.Mission;
import static pv168.agencymanager.swing.NewAgentDialog.logger;
import pv168.common.DBUtils;

/**
 *
 * @author vlado
 */
public class NewMissionDialog extends javax.swing.JDialog {
   
    private ResourceBundle strings;
    public static final Logger logger = Logger.getLogger(NewAgentDialog.class.getName());
    private DaysMonthsYears daysMonthsYears;
    private MissionsTableModel tableModel;
    
    
    public NewMissionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.strings = strings;
        this.tableModel = tableModel;
        daysMonthsYears = new DaysMonthsYears(getLocale());
        
        jComboBoxDay.setModel(new DefaultComboBoxModel(daysMonthsYears.DAYS));
        jComboBoxMonth.setModel(new DefaultComboBoxModel(daysMonthsYears.MONTHS));
        jComboBoxYear.setModel(new DefaultComboBoxModel(daysMonthsYears.YEARS));

        this.setTitle(strings.getString("addNewMission"));

        jButtonAddMission.setText(strings.getString("addMission"));
        jButtonCancel.setText(strings.getString("cancel"));

        jLabelLabel.setText(strings.getString("newMission"));
        jLabelCodeName.setText(strings.getString("codeName") + ":");
        jLabelDateCreated.setText(strings.getString("dateCreated") + ":");
        jLabelMaxNumAgents.setText(strings.getString("maxNumberOfAgents") + ":");  
        jLabelInProgress.setText(strings.getString("inProgress") + ":");   
        jLabelNotes.setText(strings.getString("notes") + ":");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodeName = new javax.swing.JLabel();
        jTextFieldCodeName = new javax.swing.JTextField();
        jLabelDateCreated = new javax.swing.JLabel();
        jLabelMaxNumAgents = new javax.swing.JLabel();
        jLabelInProgress = new javax.swing.JLabel();
        jCheckBoxInProgress = new javax.swing.JCheckBox();
        jButtonAddMission = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelLabel = new javax.swing.JLabel();
        jLabelNotes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNotes = new javax.swing.JTextArea();
        jComboBoxDay = new javax.swing.JComboBox();
        jComboBoxMonth = new javax.swing.JComboBox();
        jComboBoxYear = new javax.swing.JComboBox();
        jTextFieldMaxAgents = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelCodeName.setText("Code Name:");

        jLabelDateCreated.setText("Date Created:");

        jLabelMaxNumAgents.setText("Max num of Agents:");

        jLabelInProgress.setText("In Progress:");

        jButtonAddMission.setText("Add Mission");
        jButtonAddMission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMissionActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");

        jLabelLabel.setText("NEW MISSION");

        jLabelNotes.setText("Notes:");

        jTextAreaNotes.setColumns(20);
        jTextAreaNotes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNotes);

        jComboBoxDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelInProgress)
                    .addComponent(jLabelMaxNumAgents)
                    .addComponent(jLabelDateCreated)
                    .addComponent(jLabelCodeName)
                    .addComponent(jButtonAddMission)
                    .addComponent(jLabelNotes))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodeName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxInProgress)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldMaxAgents, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonCancel)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLabel)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelLabel)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodeName)
                    .addComponent(jTextFieldCodeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelDateCreated))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaxNumAgents)
                    .addComponent(jTextFieldMaxAgents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxInProgress)
                    .addComponent(jLabelInProgress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNotes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonAddMission))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddMissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMissionActionPerformed
       Mission mission = new Mission();

        // Code Name
        if (jTextFieldCodeName.getText() == null) {
            JOptionPane.showMessageDialog(rootPane, strings.getString("error_name_null"), strings.getString("error"), JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Error: inserted code name was NULL");
            return;
        } else {
            mission.setCodeName(jTextFieldCodeName.getText());
        }
        
        // Date created
        mission.setDateCreated(DBUtils.date(jComboBoxYear.getSelectedItem() + "-" + (jComboBoxMonth.getSelectedIndex() + 1) +
                "-" + jComboBoxDay.getSelectedItem()));
        
        // Number of max agents on mission
        try {
            Integer i = Integer.parseInt(jTextFieldMaxAgents.getText());
            if (i < 0) {
                JOptionPane.showMessageDialog(rootPane, strings.getString("error_negative_number"),
                        strings.getString("error"), JOptionPane.ERROR_MESSAGE);
                logger.log(Level.SEVERE, "Error: inserted number was lower than 0");
                return;
            } else {
                mission.setMaxNumberOfAgents(i);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, strings.getString("error_not_a_number"),
                    strings.getString("error"), JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Error: inserted number was not a legal number");
            return;
        }
        
        // Is in progress
        mission.setInProgress(jCheckBoxInProgress.isSelected());
        
        // Notes
        mission.setNotes(jTextAreaNotes.getText());
        
        tableModel.add(mission);
        logger.log(Level.SEVERE, "Mission was added to table.");
        
        this.dispose();
    }//GEN-LAST:event_jButtonAddMissionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMissionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMissionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMissionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMissionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewMissionDialog dialog = new NewMissionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddMission;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JCheckBox jCheckBoxInProgress;
    private javax.swing.JComboBox jComboBoxDay;
    private javax.swing.JComboBox jComboBoxMonth;
    private javax.swing.JComboBox jComboBoxYear;
    private javax.swing.JLabel jLabelCodeName;
    private javax.swing.JLabel jLabelDateCreated;
    private javax.swing.JLabel jLabelInProgress;
    private javax.swing.JLabel jLabelLabel;
    private javax.swing.JLabel jLabelMaxNumAgents;
    private javax.swing.JLabel jLabelNotes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaNotes;
    private javax.swing.JTextField jTextFieldCodeName;
    private javax.swing.JTextField jTextFieldMaxAgents;
    // End of variables declaration//GEN-END:variables
}
